print("Welcome to the band name generator.")
city_name = input("What's the name of the city you grew up in?\n")
print(city_name)
pet_name = input("What's the name ofyour pet?\n")
print(pet_name)
print("Your band name could be "+city_name+" "+pet_name)
